version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"